[project]
name = "superconductors"
version = "0.1.0"
description = "Add your description here"
requires-python = ">=3.13"
dependencies = [
    "grad-cam>=1.5.5",
    "matplotlib>=3.10.6",
    "mendeleev>=1.1.0",
    "numpy>=2.3.3",
    "periodictable>=2.0.2",
    "pip>=25.2",
    "polars>=1.33.1",
    "pymatgen>=2025.6.14",
    "scikit-learn>=1.7.2",
    "seaborn>=0.13.2",
    "xgboost>=3.0.5",
]

[dependency-groups]
dev = [
    "ipykernel>=6.30.1",
]
